version: "3.8"

services:
  # Service for nginx proxy. This is the entry point.
  theseus-nginx:
    container_name: theseus-nginx
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro,Z
      - ./nginx/certs:/etc/ssl/certs:ro,Z
      - ./nginx/private:/etc/ssl/private:ro,Z
      - ./public:/usr/share/nginx/html:ro,Z
    depends_on:
      - theseus

  # Set environment variables as needed, especially JWT_SECRET as this determines
  # JWT authentication security.
  # Make sure the DATABASE_URL points to the db service.
  theseus:
    container_name: theseus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@theseus-db:5432/postgres
      - JWT_SECRET=my_jwt_secret
      - PORT=3000
      - ADMINJS_COOKIE_PASSWORD=secret_theseus_adminjs_cookie_password
      - ADMINJS_COOKIE_NAME=theseus_adminjs
      - ADMIN_EMAIL=admin
      - ADMIN_PASSWORD=admin
    volumes:
      - .:/usr/src/app:Z
    ports:
      - "3000:3000"
    depends_on:
      - db

  theseus-dev:
    container_name: theseus-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@theseus-db:5432/postgres
      - JWT_SECRET=my_jwt_secret
      - PORT=3000
      - ADMINJS_COOKIE_PASSWORD=secret_theseus_adminjs_cookie_password
      - ADMINJS_COOKIE_NAME=theseus_adminjs
      - ADMIN_EMAIL=admin
      - ADMIN_PASSWORD=admin
    volumes:
      - .:/usr/src/app:Z
    ports:
      - "3000:3000"
    depends_on:
      - db

  theseus-test:
    container_name: theseus-test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - JWT_SECRET=my_jwt_secret
      - PORT=3000
    volumes:
      - .:/usr/src/app:Z

  # Service for the Postgres database. Set user, password, db in the environment variables below.
  db:
    container_name: theseus-db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  # Volume for persisting Postgres data
  db_data:
