version: "3.8"

services:
  nginx:
    container_name: theseus_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  api:
    container_name: theseus_api
    build: ./api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@theseus_db:5432/postgres
      - JWT_SECRET=my_jwt_secret
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: theseus_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
