version: "3.8"

services:
  # Service for nginx proxy. This is the entry point.
  nginx:
    container_name: theseus_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
      - client-build

  # Service to build the client application. Output is in ./client/dist which is mounted to nginx.
  client-build:
    container_name: theseus_client_build
    build:
      context: ./client
      dockerfile: Dockerfile.build
    volumes:
      - ./client/dist:/usr/src/client/dist:Z

  # Service for the API. See Dockerfile in ./api. Set environment variables as needed,
  # especially JWT_SECRET as this determines JWT authentication security.
  # Make sure the DATABASE_URL points to the db service.
  api:
    container_name: theseus_api
    build: ./api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@theseus_db:5432/postgres
      - JWT_SECRET=my_jwt_secret
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  client-dev:
    container_name: theseus_client_dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/client:Z
    ports:
      - "5173:5173"

  api-dev:
    container_name: theseus_api_dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@theseus_db:5432/postgres
      - JWT_SECRET=my_jwt_secret
      - PORT=3000
    volumes:
      - ./api:/usr/src/api:Z
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Service for the Postgres database. Set user, password, db in the environment variables below.
  db:
    container_name: theseus_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  # Volume for persisting Postgres data
  db_data:
