version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: thesis-postgres
    environment:
      POSTGRES_USER: thesis_user
      POSTGRES_PASSWORD: thesis_password
      POSTGRES_DB: thesis_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data:
