openapi: 3.0.0
info:
  title: CEID Web Project API
  description: API documentation for the CEID Web Project
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Unauthorized - Invalid credentials
  /auth/logout:
    post:
      summary: User logout
      responses:
        "200":
          description: Logout successful
        "401":
          description: Unauthorized - Not logged in
  /users/me:
    get:
      summary: Get current user information
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
        "401":
          description: Unauthorized - Not logged in
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: User ID
    get:
      summary: Get user information by ID
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
        "404":
          description: User not found
        "403":
          description: Forbidden - Access denied
  /topics:
    get:
      summary: View all topics
      responses:
        "200":
          description: Query successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Create a topic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "201":
          description: Topic created successfully
        "400":
          description: Invalid request data
  /topics/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Topic ID
    get:
      summary: View a topic
      responses:
        "200":
          description: Query successful
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid request data
        "404":
          description: Topic not found
