openapi: 3.0.0
info:
  title: CEID Web Project API
  description: API documentation for the CEID Web Project
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /topics:
    get:
      summary: View all topics
      responses:
        "200":
          description: Query successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Create a topic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "201":
          description: Topic created successfully
        "400":
          description: Invalid request data
  /topics/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Topic ID
    get:
      summary: View a topic
      responses:
        "200":
          description: Query successful
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid request data
        "404":
          description: Topic not found
